using Roaa.Rosas.Common.Localization;

namespace Roaa.Rosas.Application.SystemMessages
{
    public enum ErrorMessage
    {
        [Localization(
               En = "Invalid email or password",
               Ar = "بيانات الحساب المدخلة غير صحيحة")]
        InvalidLogin = 2001,


        [Localization(
               En = "Invalid client credential",
               Ar = "بيانات اعتماد العميل غير صحيحة")]
        InvalidClientCredential = 2002,


        [Localization(
               En = "The account is already existed",
               Ar = "الحساب موجود مسبقا")]
        AccountAlreadyExist = 2003,


        [Localization(
               En = "The account is deactivated. Please contact the system administrator",
               Ar = "تم إيقاف الحساب, يرجى الإتصال بمسؤول النظام")]
        AccountDeactivated = 2004,


        [Localization(
               En = "You must confirm your email account",
               Ar = "يجب أن تقوم بتوثيق حساب البريد الإلكتروني الخاص بك")]
        UserMustConfirmTheirEmailAccount = 2005,



        [Localization(
               En = "The name is already used",
               Ar = "الاسم مستخدم مسبقاً")]
        NameAlreadyUsed = 3001,


        [Localization(
               En = "The Tenant has already been activated.",
               Ar = "تم التفعيل بالفعل")]
        TenantaAlreadyActivated = 3002,


        [Localization(
               En = "The Tenant has already been deactivated.",
               Ar = "تم إلغاء التفعيل بالفعل")]
        TenantaAlreadyDeactivated = 3003,


        [Localization(
               En = "The Tenant has already been deleted.",
               Ar = "تم الحذف بالفعل")]
        TenantaAlreadyDeleted = 3003,


        [Localization(
               En = "The Url is already existed",
               Ar = "عنوان الرابط موجود مسبقا")]
        UrlAlreadyExist = 3004,


        [Localization(
               En = "Deleting is not allowed",
               Ar = "الحذف غير مسموح به")]
        DeletingIsNotAllowed = 3005,

        [Localization(
               En = "Modification or deletion is not allowed for this resource due to an existing subscription",
               Ar = "لا يمكن التعديل أو الحذف لوجود اشتراك")]
        ModificationOrIsNotAllowedDueToSubscription = 3006,


        [Localization(
               En = "You can not duplicate specifications ids",
               Ar = "لا يمكنك تكرار معرفات المحددات ")]
        SpecificationsIdsDuplicated = 3007,


        [Localization(
               En = "You are not allowed to change the tenant's status",
               Ar = "لا يسمح لكم بتغيير حالة المستأجر")]
        NotAllowedChangeStatus = 3008,


        [Localization(
               En = "The Subscription Rest Url is not existed",
               Ar = "عنوان رابط إعادة تعيين الاشتراك غير موجود")]
        RestUrlNotExist = 3009,


        [Localization(
           En = "You have already upgraded/downgraded the subscription",
           Ar = "لقد قمت بترقية/تخفيض الاشتراك مسبقاً")]
        SubscriptionAlreadyUpgradedDowngraded = 3010,


        [Localization(
        En = "This plan does not belong to the product",
        Ar = "هذه الخطة لا تنتمي إلى المنتج")]
        PlanDoesNotBelongToProduct = 3011,

        [Localization(
        En = "'Password' must equal to 'Confirm Password'",
        Ar = "غير مطابقة لكلمة المرور")]
        PasswordAndConfirmMustEqual = 3012,

        [Localization(
        En = "This record has been automatically generated by the system and is crucial for system functionality. Modifying or deleting this record is restricted to maintain data integrity.",
        Ar = "تم إنشاء هذا السجل تلقائيًا بواسطة النظام ويعتبر اساسيا لوظائف النظام. التعديل أو الحذف عن هذا السجل تم تقييده لضمان تكامل البيانات")]
        ModificationOrIsNotAllowedDueLockedBySystem = 3013,

        [Localization(
        En = "A planned plan not allowed be customized or unlimited cycle.",
        Ar = "الخطة العادية لا يمكن ان تكون لها مدة مخصصة أو غير محدودة")]
        PlannedPlanCannotBeCustomized = 3014,

        [Localization(
        En = "Limited and unlimited plans have to be free (price = 0)",
        Ar = "يجب أن تكون الخطط المحدودة وغير المحدودة مجانية - السعر = 0 ")]
        LimitedAndUnlimitedPlansHaveToBeFree = 3015,

        [Localization(
        En = "Unlimited plans have to be unlimited cycle",
        Ar = "يجب أن تكون الخطط غير المحدودة ذات دورة غير محدودة")]
        UnlimitedPlansHaveToBeUnlimitedCycle = 3016,

        [Localization(
        En = "You have to select a payment method",
        Ar = "يجب تحديد طريقة الدفع")]
        SelectPaymentMethod = 3017,

    }
}
